# Generated by Django 5.2.15 on 2026-06-24 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(default='anonymous@example.com', max_length=254)),
                ('resume_name', models.CharField(default='resume.pdf', max_length=255)),
                ('ats_score', models.IntegerField()),
                ('job_description', models.TextField()),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('roadmap', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
