# Generated by Django 6.0.6 on 2026-06-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('ats_score', models.IntegerField()),
                ('skills', models.JSONField()),
                ('suggestions', models.JSONField()),
                ('improvements', models.JSONField()),
                ('roadmap', models.JSONField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
